### ISSUE TITLE
Fails to compile on UE5.2: error C2665: 'GetTypeHash': none of the 5 overloads could convert all the argument types

### ISSUE THREAD

**Issue by fferri** [TriAxis-Games/RealtimeMeshComponent#251]
```
2>C:\...\Unreal Projects\MyProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\Public\RealtimeMeshCore.h(84): error C2665: 'GetTypeHash': none of the 5 overloads could convert all the argument types
2>C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\Engine\Classes\PhysicsEngine\RigidBodyIndexPair.h(64): note: could be 'uint32 GetTypeHash(const FRigidBodyIndexPair)'
2>C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\CoreUObject\Public\UObject\ObjectHandle.h(177): note: or       'uint32 GetTypeHash(UE::CoreUObject::Private::FObjectHandlePrivate)'
2>C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\CoreUObject\Public\UObject\WeakObjectPtr.h(337): note: or       'uint32 GetTypeHash(const FWeakObjectPtr &)'
2>C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\Core\Public\Containers\VersePathFwd.h(32): note: or       'uint32 GetTypeHash(const UE::Core::FVersePath &)'
2>C:\Program Files\Epic Games\UE_5.2\Engine\Source\Runtime\Core\Public\Templates\Tuple.h(776): note: or       'uint32 GetTypeHash(const TTuple<> &)'
```

and other errors:

```
2>C:\...\Unreal Projects\MyProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\Public\RenderProxy\RealtimeMeshGPUBuffer.h(155): error C2061: syntax error: identifier 'TRHIResourceUpdateBatcher'
2>C:\...\Unreal Projects\MyProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\Public\RenderProxy\RealtimeMeshGPUBuffer.h(158): error C2065: 'UpdateData': undeclared identifier
2>C:\...\Unreal Projects\MyProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\Public\RenderProxy\RealtimeMeshGPUBuffer.h(159): error C2065: 'UpdateData': undeclared identifier
2>C:\...\Unreal Projects\MyProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\Public\RenderProxy\RealtimeMeshGPUBuffer.h(160): error C2065: 'UpdateData': undeclared identifier
2>C:\...\Unreal Projects\MyProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\Public\RenderProxy\RealtimeMeshGPUBuffer.h(163): error C2065: 'UpdateData': undeclared identifier
2>C:\...\Unreal Projects\MyProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\Public\RenderProxy\RealtimeMeshGPUBuffer.h(202): error C2061: syntax error: identifier 'TRHIResourceUpdateBatcher'
2>C:\...\Unreal Projects\MyProject\Plugins\RealtimeMeshComponent\Source\RealtimeMeshComponent\Public\RenderProxy\RealtimeMeshGPUBuffer.h(206): error C2065: 'Batcher': undeclared identifier
...
```

**Comment by capnrotbart** [comment]
Same issue for me. I just created a draft PR that fixes all compile errors, but no guarantee it won't eat your project: https://github.com/TriAxis-Games/RealtimeMeshComponent/pull/252

**Comment by Koderz** [comment]
Unreal Engine 5.2 should now be fully supported! If you have any further issues feel free to reopen this or open a new issue!

Thanks,
Koderz
